jbosstools/jbosstools-integration-stack-tests

tests/org.jboss.tools.drools.ui.bot.test/pom.xml
Distribution of brms runtime is changed and downloading process should be updated.
=> Drools: Update downloading of brms runtime

plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/properties/jbpm/UserTaskTab.java
org.jboss.tools.bpmn2.ui.bot.test.testcase.editor.ParallelSplitJoinTest.executeTest default (from org.jboss.tools.bpmn2.ui.bot.test.SmokeTests)
Error Message
Unable to find ToolItem with label: Close in section: Actor Details
Stacktrace
org.jboss.reddeer.swt.exception.SWTLayerException: Unable to find ToolItem with label: Close in section: Actor Details
at org.jboss.tools.bpmn2.reddeer.editor.properties.SectionToolItem.<init>(SectionToolItem.java:50)
at org.jboss.tools.bpmn2.reddeer.properties.jbpm.UserTaskTab.addActor(UserTaskTab.java:102)
at org.jboss.tools.bpmn2.reddeer.editor.jbpm.activities.UserTask.addActor(UserTask.java:84)
at org.jboss.tools.bpmn2.ui.bot.test.testcase.editor.ParallelSplitJoinTest.buildProcessModel(ParallelSplitJoinTest.java:46)
at …
=> BPMN2: Smoke tests fail

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionTest.java
Propose a DebugAs option to start CamelContext & debug java code used by beans from camel routes
https://issues.jboss.org/browse/FUSETOOLS-853
=> Fuse: Add test covers FUSETOOLS-853

plugins/org.jboss.tools.runtime.reddeer/resources/SOARequirements.xsd, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/ServerBase.java, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/impl/ServerAS.java, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/impl/ServerKaraf.java, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/preference/InstalledJREs.java, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/wizard/ServerRuntimeWizard.java, tests/org.jboss.tools.runtime.ui.bot.test/pom.xml, tests/org.jboss.tools.runtime.ui.bot.test/resources/config/as-711-with-jre.xml
Server/runtime can be set with different java version than JBDS
=> Runtime: allow specifying other java version

tests/org.jboss.tools.switchyard.ui.bot.test/src/org/jboss/tools/switchyard/ui/bot/test/BindingsTest.java
When you run all tests then the IDE sometimes freezes, usually at BindingsTest during removing all bindings.
=> SwitchYard: tests sometimes freeze

README.md
Create a guide describes workflow - someone want to contribute to this repository
=> Documentation: Create a guide "How to contribute"

plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/debug/BreakpointsView.java, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/server/ServerManipulator.java, tests/org.jboss.tools.fuse.ui.bot.test/resources/breakpoint.bkpt, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionTest.java
Karaf cannot be started in debug mode
https://issues.jboss.org/browse/FUSETOOLS-1132
=> Fuse: Add test covers FUSETOOLS-1132

plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/debug/BreakpointsView.java, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/server/ServerManipulator.java, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/ErrorLogView.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/CamelEditorTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DebuggerTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DeploymentTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/JMXNavigatorServerTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/JMXNavigatorTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RouteManipulationTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/ServerTest.java
Add test on _Error Log_ View content during execution existing tests.
For example:
ServerTest - check error log after server is started/stopped
=> Fuse: Add test on Error Log View content

tests/org.jboss.tools.switchyard.ui.bot.test/resources/settings/plugin_customization.ini
=> SwitchYard: Get rid of "Save And launch" window

plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/impl/ServerFabric8.java, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/impl/ServerServiceMix.java, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/requirement/ServerConfig.java, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/requirement/ServerReqType.java
In JBDS 8.0.2.GA with JBDSIS 8.0.0.GA is available:
* _Apache ServiceMix 4.5 Server_
* _Apache ServiceMix 5.0 Server_
* _Fabric8 1.1 Server_
=> Runtime: Add support for Apache ServiceMix and Fabric8

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/ServerJRETest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/suite/AllTests.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/suite/ServerTests.java
see https://issues.jboss.org/browse/FUSETOOLS-1260
=> Fuse: Add test covers alternate runtime JRE

tests/org.jboss.tools.switchyard.ui.bot.test/src/org/jboss/tools/switchyard/ui/bot/test/BindingsTest.java
Not all asserts were changed by #258, mainly in JCA binding test
=> SwitchYard: Fix bindings test

tests/org.jboss.tools.switchyard.ui.bot.test/resources/projects/hello/pom.xml, tests/org.jboss.tools.switchyard.ui.bot.test/resources/projects/hello/src/test/java/com/example/switchyard/hello/HelloServiceTest.java, tests/org.jboss.tools.switchyard.ui.bot.test/src/org/jboss/tools/switchyard/ui/bot/test/DebuggerTest.java
The following issues were fixed:
- SWITCHYARD-2205: Debugger sometimes doesn't pause at service provider breakpoint
- SWITCHYARD-2424: Debugger does not work on Luna (JBDS 8)
=> SwitchYard: Finish DebuggerTest

plugins/org.jboss.tools.switchyard.reddeer/src/org/jboss/tools/switchyard/reddeer/condition/IsSuspended.java, tests/org.jboss.tools.switchyard.ui.bot.test/src/org/jboss/tools/switchyard/ui/bot/test/DebuggerTest.java
There is a bug in IsSuspended class, this wait condition every time tries to find a resume button in thw workbench but title of this workbench is changing.
=> SwitchYard: Finish DebuggerTest (fix)

pom.xml, site/pom.xml
=> Update JBT to 4.2.3.Final and JBTIS to 4.2.1.Final

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/FuseProjectTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/utils/ProjectFactory.java
After creation of some projects there could be problem with _not covered by lifecycle_ in _pom.xml_. Use _Quick fix_ on these problems.
=> Fuse: Improve 'ProjectFactory' (not covered by lifecycle)

plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/ErrorRef.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/Escalation.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/Process.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/endevents/MessageEndEvent.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/eventdefinitions/ErrorEventDefinition.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/eventdefinitions/EscalationEventDefinition.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/properties/setup/SignalSetUp.java, tests/org.jboss.tools.bpmn2.ui.bot.test/resources/bpmn2/model/base/BaseBPMN2-DefinitionViaElement.bpmn2, tests/org.jboss.tools.bpmn2.ui.bot.test/src/org/jboss/tools/bpmn2/ui/bot/complex/test/JBPM6ComplexTests.java, tests/org.jboss.tools.bpmn2.ui.bot.test/src/org/jboss/tools/bpmn2/ui/bot/complex/test/testcase/ComplexDefinitionViaElementTest.java
Create testcase, which will add definitions like (Message, Signal ...) to process via elements like (Start Event, Throw Event...), not via process properties.
=> BPMN2: new testcase for process definitions

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DebuggerTest.java
Add wait before gets value from _Variable View_
=> Fuse: Fix 'DebuggerTest'

plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/server/ServerManipulator.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DeploymentTest.java
a project is not deployed automatically after server's start - see https://issues.jboss.org/browse/FUSETOOLS-1317
Fix this behavior in test
=> Fuse: Fix 'DeploymentTest'

plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/ProcessEditorView.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/dialog/jbpm/CalledActivityDialog.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/dialog/jbpm/DataTypeDialog.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/dialog/jbpm/ExportDiagramDialog.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/dialog/jbpm/ImportJavaTypeDialog.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/dialog/jbpm/InterfaceDialog.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/dialog/jbpm/MessageDialog.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/dialog/jbpm/OperationDialog.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/dialog/jbpm/SignalDialog.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/graphiti/PropertiesGraphitiEditPart.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/ErrorRef.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/Escalation.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/Operation.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/activities/UserTask.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/catchevents/SignalIntermediateCatchEvent.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/eventdefinitions/ErrorEventDefinition.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/eventdefinitions/EscalationEventDefinition.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/eventdefinitions/SignalEventDefinition.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/properties/jbpm/InterfacesTab.java, tests/org.jboss.tools.bpmn2.ui.bot.test/src/org/jboss/tools/bpmn2/ui/bot/complex/test/testcase/ComplexIntermediateCatchSignalSingleTest.java
During setting properties via graphiti properties view, DefaultShell() returns wrong shell, it is needed to use DefaultShell(label);
=> BPMN2: do not use DefaultShell() everywhere

plugins/org.jboss.tools.switchyard.reddeer/META-INF/MANIFEST.MF, plugins/org.jboss.tools.switchyard.reddeer/src/org/jboss/tools/switchyard/reddeer/wizard/ExistingBPMNServiceWizard.java, plugins/org.jboss.tools.switchyard.reddeer/src/org/jboss/tools/switchyard/reddeer/wizard/ExistingDroolsServiceWizard.java, tests/org.jboss.tools.switchyard.ui.bot.test/src/org/jboss/tools/switchyard/ui/bot/test/ImplementationsTest.java
This is related only to
* BPMN
* Rules
=> SwitchYard: Extend implementation tests by adding non-resource implementations

plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/MessagesView.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RouteManipulationTest.java
* column with node's name was changed
* order of messages was changed
=> Fuse: Fix 'RouteManipulationTest'

plugins/org.jboss.tools.switchyard.reddeer/src/org/jboss/tools/switchyard/reddeer/editor/SwitchYardEditor.java, tests/org.jboss.tools.switchyard.ui.bot.test/src/org/jboss/tools/switchyard/ui/bot/test/ImplementationsTest.java
Sometimes a component is not deleted in ImplementationsTest.
=> SwitchYard: Sometimes a component is not deleted 

plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/SAPConnectionView.java, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/SAPDestinationProperties.java, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/SAPServerProperties.java, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/widget/CLabeledText.java, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/widget/WithCLabelMatcher.java, plugins/org.jboss.tools.runtime.reddeer/resources/SOARequirements.xsd, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/SAPConnectionTest.java
- this test will require sap-requirement
- test Destination DataSoure
- test Server DataSoure
- test exporting
=> Fuse: Create test for SAP Connection view

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionTest.java
https://issues.jboss.org/browse/FUSETOOLS-1243
=> Fuse: Add new regression test for FUSETOOLS-1243

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/CamelEditorTest.java
see https://issues.jboss.org/browse/FUSETOOLS-1378
=> Fuse: Fix code completion test

plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/projectexplorer/CamelProject.java, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/FuseProjectWizard.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/LocalCamelContextTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/utils/ProjectFactory.java
try to run as Local Camel Context a project from all available archetypes
=> Fuse: Add test for running projects as Local Camel Context

plugins/org.jboss.tools.switchyard.reddeer/src/org/jboss/tools/switchyard/reddeer/editor/SwitchYardEditor.java, plugins/org.jboss.tools.switchyard.reddeer/src/org/jboss/tools/switchyard/reddeer/utils/PreferenceUtils.java, tests/org.jboss.tools.switchyard.ui.bot.test/src/org/jboss/tools/switchyard/ui/bot/test/ImplementationsTest.java
The tests are still failing on Windows. Probably due an issue with building the project all the time, try to turn off automatic building.
=> SwitchYard: Improve stability of ImplementationsTest

plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/DataTransformationEditor.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DataTransformationTest.java
due to https://issues.jboss.org/browse/FUSETOOLS-1355
=> Fuse: Fix 'DataTransformationTest'

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionTest.java
https://issues.jboss.org/browse/FUSETOOLS-1403
=> Fuse: Add regression test for FUSETOOLS-1403

tests/pom.xml
[ERROR] Failed to execute goal on project org.jboss.tools.runtime.ui.bot.test: Could not resolve dependencies for project org.jboss.tools.runtime:org.jboss.tools.runtime.ui.bot.test:eclipse-test-plugin:4.2.0-SNAPSHOT: The following artifacts could not be resolved: org.jboss.tools.fuse:org.jboss.tools.fuse.reddeer:jar:4.2.0-SNAPSHOT, org.jboss.tools.runtime:org.jboss.tools.runtime.reddeer:jar:4.2.0-SNAPSHOT: Failure to find org.jboss.tools.fuse:org.jboss.tools.fuse.reddeer:jar:4.2.0-SNAPSHOT in http://repository.jboss.org/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-public-repository-group has elapsed or updates are forced -> [Help 1]
=> Cannot clean the project

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/CamelEditorTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DataTransformationTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DebuggerTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DefaultTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DeploymentTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DownloadServerTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/Fabric8Test.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/FabricInCloudTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/FeaturesTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/FuseProjectTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/JMXNavigatorServerTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/JMXNavigatorTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/ProjectLocalRunTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionFuseTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionKarafTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RouteManipulationTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/SAPComponentTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/SAPConnectionTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/SAPInstallationTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/ServerJRETest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/ServerTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/SmokeTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/utils/FuseArchetypeNotFoundException.java
See https://docs.google.com/document/d/1sjiuGCu7hB91YrVhfgqozPgC0g6VipWLXFu8BOeSlQM/edit#heading=h.lcjsd32som3u
The mentioned document should be created from JavaDoc comments of test classes and methods, to keep it actual.
=> Fuse: Anotate test methods with description

tests/org.jboss.tools.bpmn2.ui.bot.test/pom.xml
=> BPMN2: Tests are not executed

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/LicenseTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/suite/AllTests.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/suite/WithoutServerTests.java
https://issues.jboss.org/browse/FUSETOOLS-1389
=> Fuse: Add test for FUSETOOLS-1389 (License Agreement)

plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/projectexplorer/CamelProject.java
the test doesn't recognize successfully started _camel-archetype-web_ and _camel-archetype-spring-dm_
=> Fuse: Fix 'FuseProjectTest' (Run as Local Camel Context)

plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/debug/Breakpoint.java, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/CamelEditor.java, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/projectexplorer/CamelProject.java, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/server/ServerManipulator.java, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/Fabric8Explorer.java, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/view/JMXNavigator.java, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/ImportMavenWizard.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DefaultTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/Fabric8Test.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/FeaturesTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionFuseTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/utils/ProjectFactory.java
problem with RedDeer 0.8.0 (tests do not reflect changes in RedDeer)
=> Fuse: Fix tests for jbtis-4.2.x branch

plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/graphiti/PropertiesGraphitiEditPart.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/eventdefinitions/ErrorEventDefinition.java, tests/org.jboss.tools.bpmn2.ui.bot.test/src/org/jboss/tools/bpmn2/ui/bot/complex/test/testcase/ComplexAdHocProcessTest.java
https://projects.engineering.redhat.com/browse/RHBXMSQE-455
=> BPMN2: close dialogs before end of the test

tests/org.jboss.tools.esb.ui.bot.test/pom.xml, tests/org.jboss.tools.fuse.ui.bot.test/pom.xml, tests/org.jboss.tools.modeshape.ui.bot.test/pom.xml, tests/org.jboss.tools.runtime.ui.bot.test/pom.xml, tests/org.jboss.tools.switchyard.ui.bot.test/pom.xml, tests/pom.xml
=> Increase timeout for all tests

pom.xml
=> Update JBTIS to 4.2.4.CR2

plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/DataTransformationEditor.java
_Set field_ has been changed to _Set property_.
It is related to _jbtis-4.2.x_ branch.
=> Fuse: Reflect change in Data Transformation into tests

plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/wizard/ServerWizard.java
New Server wizard sometimes loses focus
=> Runtime: Fix problem with 'New Server' wizard

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DeploymentEAPTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/LicenseTest.java
=> Fuse: Update JavaDoc

tests/org.jboss.tools.fuse.ui.bot.test/pom.xml
jbosstools-integration-stack-tests/tests/org.jboss.tools.fuse.ui.bot.test/pom.xml
=> Fuse: Add DataTransformation feature to pom.xml

README.md, tests/README.md, tests/org.jboss.tools.bpmn2.ui.bot.test/README.md, tests/org.jboss.tools.bpmn2.ui.bot.test/launcher/BPMN2Tests.launch, tests/org.jboss.tools.drools.ui.bot.test/README.md, tests/org.jboss.tools.esb.ui.bot.test/README.md, tests/org.jboss.tools.jbpm.ui.bot.test/README.md, tests/org.jboss.tools.switchyard.ui.bot.test/README.md, tests/org.jboss.tools.teiid.ui.bot.test/README.md
- update links
- add a guide about running the tests
=> Update readme file

tests/org.jboss.tools.bpel.ui.bot.test/src/org/jboss/tools/bpel/ui/bot/test/suite/AllTests.java
Due to https://issues.jboss.org/browse/JBTIS-325
=> BPEL: Disable ExamplesTest

plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/impl/ServerAS.java, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/impl/ServerKaraf.java
due to https://issues.jboss.org/browse/JBDS-3596
=> Extend timeout when creating a new server

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/JMXNavigatorServerTest.java
https://issues.jboss.org/browse/JBTIS-584
Fuse Tooling
- tested with - JBoss Fuse Tooling 8.0.0.Beta1-v20160315-0510
=> JBTIS-584: Adapt 'JMXNavigatorServerTest' to 8.0.0

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionTest.java
https://issues.jboss.org/browse/JBTIS-591
Fuse Tooling
- tested with - JBoss Fuse Tooling 8.0.0.Beta1-v20160321-0715
=> JBTIS-591: Adapt 'RegressionTest' to 8.0.0

plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/CamelEditor.java
Fuse Tooling
- tested with JBoss Fuse Tooling 8.0.0.Beta2-v20160401-1305-B821
=> JBTIS-575: Fix for 'testXMLEditor' method in 'CamelEditorTest'

tests/org.jboss.tools.teiid.ui.bot.test/resources/projects/RecursiveCTE/.project, tests/org.jboss.tools.teiid.ui.bot.test/resources/projects/RecursiveCTE/Oracle11View.xmi, tests/org.jboss.tools.teiid.ui.bot.test/resources/projects/RecursiveCTE/Oracle_11g_bqt2.xmi, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/RecursiveCommonTableExpression.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/suite/AllTests.java
https://issues.jboss.org/browse/JBTIS-668
=> JBTIS-668 Add test for Recursive Common Table Expressions

plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/Procedure.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/UDFTest.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/suite/AllTests.java
https://issues.jboss.org/browse/JBTIS-679
=> JBTIS-679 - Add UDF Test - 4.2.x

tests/org.jboss.tools.teiid.ui.bot.test/resources/importWizard/csv-items.properties, tests/org.jboss.tools.teiid.ui.bot.test/resources/importWizard/hsql-ds1.properties, tests/org.jboss.tools.teiid.ui.bot.test/resources/importWizard/hsql-employees.properties, tests/org.jboss.tools.teiid.ui.bot.test/resources/importWizard/ldap.properties, tests/org.jboss.tools.teiid.ui.bot.test/resources/importWizard/rhds.properties, tests/org.jboss.tools.teiid.ui.bot.test/resources/importWizard/sf.properties, tests/org.jboss.tools.teiid.ui.bot.test/resources/importWizard/sqlserver.properties
https://issues.jboss.org/browse/JBTIS-710
=> JBTIS-710 Fix LDAP Import test

plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/view/ModelExplorer.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/UDFTest.java
https://issues.jboss.org/browse/JBTIS-717
=> JBTIS-717 - Fix UDF test - master

plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/view/ModelExplorer.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/UDFTest.java
https://issues.jboss.org/browse/JBTIS-717
=> JBTIS-717  - Fix UDF test

tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/JdgImportTest.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/UDFTest.java
https://issues.jboss.org/browse/JBTIS-722
=> JBTIS-722 - Fix JDG test and revert wrong fix for UDF import

plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/ModelClass.java, tests/org.jboss.tools.teiid.ui.bot.test/pom.xml
https://issues.jboss.org/browse/JBTIS-725
=> JBTIS-725 - Fix Model Wizard Test

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/SimpleTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/suite/AllTests.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/suite/SmokeTests.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/suite/WithoutServerTests.java
in order to avoid confusion what are smoke tests ('SmokeTest' or 'SmokeTests')
=> Fuse: Rename 'SmokeTest' to 'SimpleTest'

plugins/org.jboss.tools.runtime.reddeer/resources/SOARequirements.xsd, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/ServerBase.java, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/impl/ServerAS.java, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/impl/ServerKaraf.java, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/wizard/ServerRuntimeWizard.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DataTransformationDeploymentEAPTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DeploymentEAPTest.java
https://issues.jboss.org/browse/JBTIS-727
+ adjust the following Fuse Tooling tests: 'DataTransformationDeploymentEAPTest' and 'DeploymentEAPTest'
=> JBTIS-727: Extend Server requirement for Runtime Execution

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/CamelEditorTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/ConfigurationsEditorTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DebuggerTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DeploymentEAPTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DeploymentTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/FeaturesTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/FuseProjectTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/JMXNavigatorServerTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/JMXNavigatorTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/NewFuseProjectWizardTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/ProjectLocalRunTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionFuseTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RouteManipulationTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/SAPComponentTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/SimpleTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/utils/ProjectFactory.java
https://issues.jboss.org/browse/JBTIS-793
=> JBTIS-793: Fuse: Use simplified project creation methods in ProjectFactory

plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/connection/ResourceFileHelper.java, plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/dialog/ProcedureViewDialog.java, plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/editor/VDBEditor.java, plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/wizard/ProcedureWizard.java, tests/org.jboss.tools.teiid.ui.bot.test/resources/flat/RestProcedureTest/application-roles.properties, tests/org.jboss.tools.teiid.ui.bot.test/resources/flat/RestProcedureTest/insertRequest.json, tests/org.jboss.tools.teiid.ui.bot.test/resources/sql/RestProcedureTest/getProcedureGet.sql, tests/org.jboss.tools.teiid.ui.bot.test/resources/sql/RestProcedureTest/getProcedurePost.sql, tests/org.jboss.tools.teiid.ui.bot.test/resources/xml/RestProcedureTest/getResponse.xml, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/RestProcedureTest.java
https://issues.jboss.org/browse/JBTIS-804
=> JBTIS-804: Complete REST test

tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/UDFTest.java
https://issues.jboss.org/browse/JBTIS-825
=> JBTIS-825 Fix UDFImport test

tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/suite/OtherTests.java
https://issues.jboss.org/browse/JBTIS-829
=> JBTIS-829 - Add ReuseVDB test to 'Other tests' test suite

plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/editor/CamelEditor.java, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/utils/FuseServerManipulator.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/ComponentTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DataTransformationTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DeploymentEAPTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/LicenseTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/NewFuseProjectWizardTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RouteManipulationTest.java
https://issues.jboss.org/browse/JBTIS-954
=> JBTIS-954 - Fuse: Fix all automated tests for 9.0.0

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/utils/ProjectFactory.java
https://issues.jboss.org/browse/JBTIS-996
=> JBTIS-996 - Fuse: Fix error in project creation

plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/view/ServersViewExt.java, plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/wizard/connectionProfiles/noDatabase/RestConnectionProfileWizard.java, plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/wizard/connectionProfiles/noDatabase/WsdlConnectionProfileWizard.java, tests/org.jboss.tools.teiid.ui.bot.test/launcher/TeiidDesigner.launch, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/ConsumeRestWs.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/ConsumeSoapWs.java
https://issues.jboss.org/browse/JBTIS-999
=> JBTIS-999: Add Consume SOAP Digest test + update Consume REST/SOAP tests

plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/ProjectTemplate.java, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/wizard/NewFuseIntegrationProjectWizard.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/ConfigurationsEditorDataFormatsTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/ConfigurationsEditorEndpointsTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/utils/ProjectFactory.java
now takes 2 seconds instead of 13
there are still places using the less-performant way but can be improved in another PR
=> Use complete Tree path to improve performance

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/ComponentTest.java
for more information see https://issues.jboss.org/browse/JBTIS-1068
=> JBTIS-1068 - Fuse: Fix ComponentTest

tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/FuseProjectTestLong.java, tests/pom.xml
https://issues.jboss.org/browse/JBTIS-1115
=> JBTIS-1115 - Fuse: Extend 'FuseProjectTestLong'

plugins/org.jboss.tools.fuse.reddeer/META-INF/MANIFEST.MF, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/FuseConfig.java, plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/requirement/FuseRequirement.java, plugins/org.jboss.tools.runtime.reddeer/resources/SOARequirements.xsd, tests/org.jboss.tools.fuse.ui.bot.test/resources/config/karaf-3.0.3.xml, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DataTransformationDeploymentEAPTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DataTransformationDeploymentTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DeploymentEAPTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DeploymentTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/JMXNavigatorServerTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/NewFuseProjectWizardTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/QuickStartsTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionFuseTest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/ServerJRETest.java, tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/ServerTest.java
https://issues.jboss.org/browse/JBTIS-1121
=> JBTIS-1121 - Create new server requirement for Fuse on EAP

plugins/org.jboss.tools.switchyard.reddeer/src/org/jboss/tools/switchyard/reddeer/component/SwitchYardComponent.java, tests/org.jboss.tools.switchyard.ui.bot.test/src/org/jboss/tools/switchyard/ui/bot/test/DebuggerBreakpointTest.java
Signed-off-by: Andrej Podhradsky <apodhrad@redhat.com>
=> JBTIS-1154: SY - Apply oxygen changes in debugger tests

plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/impl/ServerFuse.java, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/impl/ServerKaraf.java, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/preference/FuseServerRuntimePreferencePage.java, plugins/org.jboss.tools.runtime.reddeer/src/org/jboss/tools/runtime/reddeer/wizard/FuseServerWizard.java
https://issues.jboss.org/browse/JBTIS-1163
=> JBTIS-1163 - Fuse - Adapt Server category change in tests

plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/activities/ReceiveTask.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/activities/SendTask.java, tests/org.jboss.tools.bpmn2.ui.bot.test/resources/bpmn2/model/base/BaseBPMN2-MessageStart.bpmn2, tests/org.jboss.tools.bpmn2.ui.bot.test/src/org/jboss/tools/bpmn2/ui/bot/complex/test/testcase/ComplexMessageStartTest.java
Introduce update to bpmn2 message task framework.
Modify bpmn2 process to create a new message at start.
=> [jbtis-4.5.x] JBTIS-1181: Fix unstable bpmn2 message test

plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/activities/ReceiveTask.java, plugins/org.jboss.tools.bpmn2.reddeer/src/org/jboss/tools/bpmn2/reddeer/editor/jbpm/activities/SendTask.java, tests/org.jboss.tools.bpmn2.ui.bot.test/resources/bpmn2/model/base/BaseBPMN2-MessageStart.bpmn2, tests/org.jboss.tools.bpmn2.ui.bot.test/src/org/jboss/tools/bpmn2/ui/bot/complex/test/testcase/ComplexMessageStartTest.java
Master fixes for unsatble tests
Introduce update to bpmn2 message task framework.
Modify bpmn2 process to create a new message at start.
Signed-off-by: domhanak <dhanak@redhat.com>
=> JBTIS-1181: Fix unstable bpmn2 message test

plugins/org.jboss.tools.drools.reddeer/src/org/jboss/tools/drools/reddeer/editor/NestedEditor.java
Signed-off-by: Tomas David <tdavid@redhat.com>
=> Drools: fix Editor reddeer changes

plugins/org.jboss.tools.switchyard.reddeer/src/org/jboss/tools/switchyard/reddeer/editor/SwitchYardEditor.java
Signed-off-by: Andrej Podhradsky <apodhrad@redhat.com>
=> JBTIS-1206: Test SwitchYardEditorValidatorsTest is sometimes failing

plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/dialog/MaterializationDialog.java, plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/editor/ModelEditor.java, plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/view/ModelExplorer.java, plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/wizard/connectionProfiles/noDatabase/Jdg7ConnectionProfileWizard.java, tests/org.jboss.tools.teiid.ui.bot.test/resources/projects/ProductsProject/.project, tests/org.jboss.tools.teiid.ui.bot.test/resources/projects/ProductsProject/ProductsSource.xmi, tests/org.jboss.tools.teiid.ui.bot.test/resources/projects/ProductsProject/ProductsView.xmi, tests/org.jboss.tools.teiid.ui.bot.test/resources/sql/Reproducers/parentheses.sql, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/reproducers/TeiidDes2888Test.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/reproducers/TeiidDes3106Test.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/reproducers/TeiidDes3125Test.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/reproducers/TeiidDes3133Test.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/suite/ReproducersTest.java
Reproducers for Teiid Designer 11.1.1
https://issues.jboss.org/browse/TEIIDDES-3125
https://issues.jboss.org/browse/TEIIDDES-3133
https://issues.jboss.org/browse/TEIIDDES-3106
https://issues.jboss.org/browse/TEIIDDES-2888
=> JBTIS-1215 Reproducers for Teiid Designer 11.1.1

plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/connection/ConnectionProfileConstants.java, plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/connection/ConnectionProfileHelper.java, plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/wizard/connectionProfiles/noDatabase/RestConnectionProfileWizard.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/ConsumeRestWs.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/ConsumeSoapWs.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/GuidesTest.java
Signed-off-by: mkralik3 <mkralik@redhat.com>
//TABs was changed to SPACEs so the code may look unformatted but this is only in the GitHub view. In the IDE it looks great.
=> JBTIS-1211 Update REST / SOAP Web Service in the teiid tests

plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/ImportHelper.java, plugins/org.jboss.tools.teiid.reddeer/src/org/jboss/tools/teiid/reddeer/editor/VdbEditor.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/GeometryTypeTest.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/ImportModelTest.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/LdapImportTest.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/SalesforceImportTest.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/VDBEditorTest.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/imports/H2.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/imports/HSql.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/imports/Modeshape.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/imports/Oracle.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/imports/PostgreSql.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/imports/SapHana.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/imports/SqlServer.java, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/suite/ImportTests.java
Signed-off-by: mmajerni <mmajerni@redhat.com>
=> Designer 11.1.3 small fixes

tests/org.jboss.tools.teiid.ui.bot.test/resources/sql/PreviewModelTest/multipleQueries.sql, tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/PreviewModelTest.java
Signed-off-by: mmajerni <mmajerni@redhat.com>
=> Add test for multiple queries in scrapbook

pom.xml, tests/org.jboss.tools.bpel.ui.bot.test/META-INF/MANIFEST.MF, tests/org.jboss.tools.bpmn2.ui.bot.test/META-INF/MANIFEST.MF, tests/org.jboss.tools.drools.ui.bot.test/META-INF/MANIFEST.MF
Signed-off-by: Andrej Podhradsky <apodhrad@redhat.com>
=> JBTIS-1245: Update UI tests for JDK 11
