jbosstools/jbosstools-integration-stack-tests

- tests/org.jboss.tools.bpmn2.ui.bot.test/src/org/jboss/tools/bpmn2/ui/bot/test/JBPM6BaseTest.java
Always the second test fails on Windows. The palette tools and the process itself is not rendered correctly.
Note that we were not able to reproduce this manually.
> BPMN2: Tests fail on Windows

- plugins/org.jboss.tools.switchyard.reddeer/src/org/jboss/tools/switchyard/reddeer/project/SwitchYardProject.java
- tests/org.jboss.tools.switchyard.ui.bot.test/src/org/jboss/tools/switchyard/ui/bot/test/ProjectCreationTest.java
Error Message
No control has focus. Perhaps something has stolen it? Try to regain focus with for example "new DefaultShell()".
Stacktrace
org.jboss.reddeer.swt.exception.SWTLayerException: No control has focus. Perhaps something has stolen it? Try to regain focus with for example "new DefaultShell()".
at org.jboss.reddeer.swt.lookup.MenuLookup.getTopMenuMenuItemsFromFocus(MenuLookup.java:175)
at org.jboss.reddeer.swt.impl.menu.ContextMenu.<init>(ContextMenu.java:42)
at org.jboss.reddeer.swt.impl.menu.ContextMenu.<init>(ContextMenu.java:33)
at org.jboss.tools.switchyard.reddeer.project.SwitchYardProject.update(SwitchYardProject.java:55)
at org.jboss.tools.switchyard.ui.bot.test.ProjectCreationTest.createProjectWithComponentsTest(ProjectCreationTest.java:192)
at …
> SwitchYard: Smoke tests fail on RHEL 7

- tests/org.jboss.tools.drools.ui.bot.test/pom.xml
Distribution of brms runtime is changed and downloading process should be updated also for jbtis-4.1.x branch.
> Drools: Update brms runtime downloading for jbtis-4.1.x branch

- plugins/org.jboss.tools.fuse.reddeer/src/org/jboss/tools/fuse/reddeer/server/ServerManipulator.java
- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionKarafTest.java
JMX Node in servers view doesn't work if server has secured JMX access via credentials
https://issues.jboss.org/browse/FUSETOOLS-1264
> Fuse: Add new regression test for FUSETOOLS-1264

- tests/org.jboss.tools.drools.ui.bot.test/pom.xml
Brms 5 binaries was downloaded from http://jawa05.englab.brq.redhat.com. The address is down and it looks like it will not be available in the future.
> Drools: Brms 5 binaries cannot be downloaded

- plugins/org.jboss.tools.switchyard.reddeer/src/org/jboss/tools/switchyard/reddeer/condition/ErrorsExist.java
- plugins/org.jboss.tools.switchyard.reddeer/src/org/jboss/tools/switchyard/reddeer/wizard/ImportMavenWizard.java
- tests/org.jboss.tools.switchyard.ui.bot.test/src/org/jboss/tools/switchyard/ui/bot/test/QuickstartsTest.java
Ignore errors such as 
Plugin execution not covered by lifecycle configuration ...
> SwitchYard: ignore some errors in quickstart tests

- tests/org.jboss.tools.fuse.ui.bot.test/pom.xml
Implicit behavior - no debug/trace logs are shown
> Fuse: Disable debug level of RedDeer logs

- tests/pom.xml
Current memory options are
-Xms512m, -Xmx1024m, -XX:PermSize=256m, -XX:MaxPermSize=512m
which is too much for some 32b Windows OS
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Error occurred during initialization of VM
Could not reserve enough space for object heap
> Fix memory options

- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DefaultTest.java
- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/ServerTest.java
Smoke Tests on JBDSIS cause failure, due to an error message from teiid designer plugin (see attached screenshot)
```
java.lang.AssertionError: null
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at org.jboss.tools.fuse.ui.bot.test.ServerTest.complexServerTest(ServerTest.java:62)
```
> Fuse: Fix 'ServerTest' (error log from Teiid plugin)

- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/DeploymentTest.java
- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/JMXNavigatorServerTest.java
- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/ServerJRETest.java
- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/ServerTest.java
Current tests accept only a Fuse server
`@Server(type = ServerReqType.Fuse, state = ServerReqState.PRESENT)`
change it to accept Apache Karaf server too
`@Server(type = {ServerReqType.Fuse, ServerReqType.Karaf}, state = ServerReqState.PRESENT)`
> Fuse: Extend current tests to accept other server types

- tests/pom.xml
You can disable JBoss Cebnral by 
```
-Dorg.jboss.tools.central.donotshow=true
```
> By default run tests without showing JBoss Central

- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionFuseTest.java
- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionTest.java
- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/suite/RegressionTests.java
Split regression tests into separate classes depend on need of a server runtime:
* RegressionTest (no runtime is needed)
* RegressionFuseTest
* Regression*Runtime*Test
> Fuse: Split regression tests (without/with a server runtime)

- plugins/org.jboss.tools.switchyard.reddeer/src/org/jboss/tools/switchyard/reddeer/condition/TableHasRow.java
- plugins/org.jboss.tools.switchyard.reddeer/src/org/jboss/tools/switchyard/reddeer/preference/implementation/ImplementationKnowledgePage.java
org.jboss.reddeer.swt.exception.WaitTimeoutExpiredException: Timeout after: 10 s.: null
at org.jboss.reddeer.swt.wait.AbstractWait.timeoutExceeded(AbstractWait.java:157)
at org.jboss.reddeer.swt.wait.AbstractWait.wait(AbstractWait.java:110)
at org.jboss.reddeer.swt.wait.AbstractWait.<init>(AbstractWait.java:75)
at org.jboss.reddeer.swt.wait.AbstractWait.<init>(AbstractWait.java:51)
at org.jboss.reddeer.swt.wait.AbstractWait.<init>(AbstractWait.java:39)
at org.jboss.reddeer.swt.wait.WaitUntil.<init>(WaitUntil.java:23)
at org.jboss.tools.switchyard.reddeer.preference.implementation.ImplementationKnowledgePage.addClass(ImplementationKnowledgePage.java:165)
at org.jboss.tools.switchyard.reddeer.preference.implementation.ImplementationKnowledgePage.addItem(ImplementationKnowledgePage.java:141) …
> SwitchYard: Increase timeout when waiting on a class

- tests/org.jboss.tools.bpmn2.ui.bot.test/pom.xml
Because maven-dependency-plugin:copy-dependencies is skipped, so there are not libraries in the folder lib. I have no idea why it is skipped (and only on jbtis-4.3.x).
> BPMN2: Cannot build org.jboss.tools.bpmn2.ui.bot.test

- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/suite/SmokeTests.java
Windows
```
INFO [WorkbenchTestable][JMXNavigator] Child items of 'Local Processes' are: 
c:\hudson\slave.jar [2472][Disconnected]
Eclipse Runtime Workbench [2328][Disconnected]
maven [2088][Disconnected]
maven [3048][Disconnected]
INFO [WorkbenchTestable][JMXNavigator] Trying to identify the right process
INFO [WorkbenchTestable][JMXNavigator] Looking for 'Local Camel Context' item
INFO [WorkbenchTestable][AbstractTreeItem] Select tree item maven [2088][Disconnected]
INFO [WorkbenchTestable][TreeItemHandler] Selected tree item: maven [2088][Disconnected]
INFO [WorkbenchTestable][AbstractTreeItem] Double click tree item maven [2088][Disconnected]
INFO [WorkbenchTestable][AbstractTreeItem] Select tree item maven [2088][Disconnected]
INFO [WorkbenchTestable][TreeItemHandler] Selected tree …
```
> Fuse: Fix failing 'SmokeTests'

- tests/org.jboss.tools.drools.ui.bot.test/src/org/jboss/tools/drools/ui/bot/test/util/RestClient.java
Base64 class is in jdk since 1.8 version at it is not compatible with older versions.
> Drools: replace java.util.Base64

- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/FuseProjectTest.java
Some archetypes are no longer shipped (they are not listed in _New Fuse Project_ wizard). This cause a serious trouble to _FuseProjectTest_, which is unable to start.
> Fuse: Fix 'FuseProjectTest'

- tests/org.jboss.tools.teiid.ui.bot.test/src/org/jboss/tools/teiid/ui/bot/test/ModelWizardTest.java
Error Message
Timeout after: 60 s.: at least one job is running
Stacktrace
org.jboss.reddeer.common.exception.WaitTimeoutExpiredException: Timeout after: 60 s.: at least one job is running
at org.jboss.reddeer.common.wait.AbstractWait.timeoutExceeded(AbstractWait.java:159)
at org.jboss.reddeer.common.wait.AbstractWait.wait(AbstractWait.java:112)
at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:77)
at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:53)
at org.jboss.reddeer.common.wait.WaitWhile.<init>(WaitWhile.java:35)
at org.jboss.reddeer.jface.wizard.WizardDialog.finish(WizardDialog.java:136)
at org.jboss.reddeer.jface.wizard.WizardDialog.finish(WizardDialog.java:121)
at org.jboss.tools.teiid.reddeer.wizard.ModelProjectWizard.create(ModelProjectW …
> Teiid: Failing ModelWizardTest

- tests/org.jboss.tools.fuse.ui.bot.test/README.md
Information of how to run tests may differ in different versions of the tooling. README file is under version control, so it reflects current state of how to run Fuse Tooling tests
wiki: https://github.com/jbosstools/jbosstools-integration-stack-tests/wiki/JBoss-Fuse-Tooling
> Fuse: Move documentation of Fuse Tooling tests from wiki to README

- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/FuseProjectTest.java
- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/LicenseTest.java
- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/QuickStartsTest.java
- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionKarafTest.java
* FuseProjectTest - data()
* LicenseTest - data()
* QuickStartsTest - defaultSetup()
* RegressionKarafTest - steupClean()
Convention:
* test methods --> test*
* auxiliary methods (Before, After, Parameters, ...) --> setup*
> Fuse: Correct wrong names of methods

- tests/org.jboss.tools.fuse.ui.bot.test/src/org/jboss/tools/fuse/ui/bot/test/RegressionTest.java
- fix problem with non existing run configuration type 'Apache Tomcat'
> JBTIS-862: Fuse: Fix errors in Regression tests
